In [5]:
import itertools
RRR = RealField(100);

def accprob(transmatrices,sigma):
    assert transmatrices[0].nrows() == transmatrices[0].ncols() == transmatrices[1].nrows() == transmatrices[1].ncols();
    n = transmatrices[0].nrows();
    Id = identity_matrix(n);
    v = Matrix(Id[0]);
    
    A = v*Id;
    for ch in sigma:
        assert int(ch) == 0 or int(ch) == 1;
        A = A*transmatrices[int(ch)];
    return A[0][n-1];


def probmatrix(transmatrices,sigma):
    assert transmatrices[0].nrows() == transmatrices[0].ncols() == transmatrices[1].nrows() == transmatrices[1].ncols();
    A = identity_matrix(transmatrices[0].nrows());
    for ch in sigma:
        assert int(ch) == 0 or int(ch) == 1;
        A = A*transmatrices[int(ch)];
    return A;
    

def list_probsold(transmatrices,upto=11,startfrom=1):
    assert transmatrices[0].nrows() == transmatrices[0].ncols() == transmatrices[1].nrows() == transmatrices[1].ncols();
    n = transmatrices[0].nrows();
    Id = identity_matrix(n);
    v = Matrix(Id[0]);
    
    strings = [];
    for i in range(startfrom,upto):
        l = list(itertools.product([0,1],repeat=i));
        for st in l:
            strings.append(st);

    problist = []; #list of strings with their acceptance probabilities
    for st in strings:   
        A = v*Id;
        for ch in st:
            assert int(ch) == 0 or int(ch) == 1;
            A = A*transmatrices[int(ch)];
        problist.append((st,A[0][n-1]));
    return problist;
    
def list_probs(transmatrices,upto=11,startfrom=1):
    assert transmatrices[0].nrows() == transmatrices[0].ncols() == transmatrices[1].nrows() == transmatrices[1].ncols();
    n = transmatrices[0].nrows();
    Id = identity_matrix(n);
    v = Matrix(Id[0]);
    
    problist = []; #list of strings with their acceptance probabilities
    for i in range(startfrom,upto):
        l = list(itertools.product([0,1],repeat=i));
        for st in l:
            #strings.append(st);
            A = v*Id;
            for ch in st:
                assert int(ch) == 0 or int(ch) == 1;
                A = A*transmatrices[int(ch)];
            problist.append((st,A[0][n-1]));
        
    return problist;
    
#expects a list in exactly the format returned by list_probs
def highest_prob(problist):
    highprob = max([l[1] for l in problist]);
    highstr = [st for st in problist if st[1] == highprob];
    return highstr;
    
def sortproblist(problist):
    return sorted(problist,key=lambda x:x[1],reverse=True);
    
    
#check transition matrices for rows summing to 1 (except last row)
def checkmatrices(P):
    assert P[0].nrows() == P[0].ncols() == P[1].nrows() == P[1].ncols();
    n = P[0].nrows();
    
    for i in range(2):
        for j in range(n-1):
            s = sum(P[i][j]);
            if s != 1:
                print "P"+str(i)+" row "+str(j+1)+" sum is "+str(RRR(s));

In [6]:
P = [Matrix([[.998,.001,.001],[.998,.001,.001],[0,0,1]]), Matrix([[.5,.499,.001],[.596,.4,.004],[0,0,1]])];
checkmatrices(P)

problist = list_probs(P,13);
print highest_prob(problist);
#print sortproblist(problist);

[((1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1), 0.0268033071142567)]

In [20]:
P0 = [Matrix(QQ,[[.5,.49,.01],[.4,.58,.02],[0,0,1]]), Matrix(QQ,[[.39,.6,.01],[.29,.7,.01],[0,0,1]])];
checkmatrices(P0)

problist = list_probs(P0,13);
high = highest_prob(problist);
print high,RR(high[0][1]);
#print sortproblist(problist);

[((1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0), 162737246786634638719/976562500000000000000)] 0.166642940709514

In [21]:
P00 = [Matrix(QQ,[[.3,.3,.3,.1],[.4,.2,.3,.1],[.4,.2,.3,.1],[0,0,0,1]]), Matrix(QQ,[[.4,.43,.1,.07],[.05,.6,.1,.25],[.05,.89,.05,.01],[0,0,0,1]])];
checkmatrices(P00)

problist = list_probs(P00,15);
high = highest_prob(problist);
print high,RR(high[0][1]);

[((0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1), 60487622209577708804359/64000000000000000000000)] 0.945119097024652

In [7]:
P1 = [Matrix(QQ,[[.4,.4999999,.1,.0000001],[.1,.5,.3999,.0001],[.3,.5,.199999,.000001],[0,0,0,1]]), Matrix(QQ,[[.4,.4,.199999,.000001],[.399998,.4,.2,.000002],[.3,.3,.3999999,.0000001],[0,0,0,1]])];
checkmatrices(P1)

problist = list_probs(P1,13);
high = highest_prob(problist);
print high,RR(high[0][1]);
#print sortproblist(problist);

[((0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0), 55310790615860048767812367185826011746771343191937479215136422753999/100000000000000000000000000000000000000000000000000000000000000000000000)] 0.000553107906158600

In [11]:
P2 = [Matrix(QQ,[[.4,.4999999,.1,.0000001],[.1,.5,.39999,.00001],[.3,.5,.199999,.000001],[0,0,0,1]]), Matrix(QQ,[[.4,.4,.199999,.000001],[.399998,.4,.2,.000002],[.3,.3,.3999999,.0000001],[0,0,0,1]])];
checkmatrices(P2)

problist = list_probs(P2,13);
high = highest_prob(problist);
print high,RR(high[0][1]);
#print sortproblist(problist);

[((0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0), 58220908856769362486100569238856239271756400461855702818301756279999/1000000000000000000000000000000000000000000000000000000000000000000000000)] 0.0000582209088567694

In [8]:
P3 = [Matrix(QQ,[[.4,.4999999,.1,.0000001],[.1,.5,.399999,.000001],[.3,.5,.199999,.000001],[0,0,0,1]]), Matrix(QQ,[[.4,.4,.199999,.000001],[.399998,.4,.2,.000002],[.3,.3,.3999999,.0000001],[0,0,0,1]])];
checkmatrices(P3)

problist = list_probs(P3,14);
high = highest_prob(problist);
print high,RR(high[0][1]);
#print sortproblist(problist);

[((1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1), 14887405423878273668438236352712381058557252213067564646301936065296092178393471800001/1000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000)] 0.0000148874054238783

In [12]:
P4 = [Matrix(QQ,[[.4,.4999999,.1,.0000001],[.1,.5,.399999,.000001],[.3,.5,.199999,.000001],[0,0,0,1]]), Matrix(QQ,[[.4,.4,.19999999,.00000001],[.399998,.4,.2,.000002],[.3,.3,.3999999,.0000001],[0,0,0,1]])];
checkmatrices(P4)

problist = list_probs(P4,14);
high = highest_prob(problist);
print [h[0] for h in high],RR(high[0][1]);
#print sortproblist(problist);

[(0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1)] 0.0000103571635975503

In [27]:
eps = RRR(.0001);
P4_2 = [Matrix(RR,[[.4,.5-eps,.1,eps],[.1,.5,.4-10*eps,10*eps],[.3,.5,.2-10*eps,10*eps],[0,0,0,1]]), Matrix(RR,[[.4,.4,.2-eps/10,eps/10],[.4-18*eps,.4,.2,18*eps],[.3,.3,.4-eps,eps],[0,0,0,1]])];
checkmatrices(P4_2)

problist = list_probs(P4_2,14);
high = highest_prob(problist);
print [h[0] for h in high],RR(high[0][1]);

[(0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1)] 0.00971084800304101

In [13]:
#R4 = PolynomialRing(QQ,32,'x');
R4 = PolynomialRing(QQ,names=('p11','p12','p13','p14','p21','p22','p23','p24','p31','p32','p33','p34','x0','x1','x2','x3','q11','q12','q13','q14','q21','q22','q23','q24','q31','q32','q33','q34','y0','y1','y2','y3'));
Q0 = matrix(R4,4,4,R4.gens()[0:16]);
Q0[3] = [0,0,0,0];
Q1 = matrix(R4,4,4,R4.gens()[16:32]);
Q1[3] = [0,0,0,0];
print Q0
print ""
print Q1
v1 = matrix(identity_matrix(4)[0]);

[p11 p12 p13 p14]
[p21 p22 p23 p24]
[p31 p32 p33 p34]
[  0   0   0   0]

[q11 q12 q13 q14]
[q21 q22 q23 q24]
[q31 q32 q33 q34]
[  0   0   0   0]

In [17]:
print accprob([Q0,Q1],"000")
print ""
print accprob([Q0,Q1],"001")
print ""
print accprob([Q0,Q1],"010")
print ""
print accprob([Q0,Q1],"100")

p11^2*p14 + p12*p14*p21 + p11*p12*p24 + p12*p22*p24 + p13*p14*p31 + p13*p24*p32 + p11*p13*p34 + p12*p23*p34 + p13*p33*p34

p11^2*q14 + p12*p21*q14 + p13*p31*q14 + p11*p12*q24 + p12*p22*q24 + p13*p32*q24 + p11*p13*q34 + p12*p23*q34 + p13*p33*q34

p11*p14*q11 + p11*p24*q12 + p11*p34*q13 + p12*p14*q21 + p12*p24*q22 + p12*p34*q23 + p13*p14*q31 + p13*p24*q32 + p13*p34*q33

p11*p14*q11 + p12*p24*q11 + p13*p34*q11 + p14*p21*q12 + p22*p24*q12 + p23*p34*q12 + p14*p31*q13 + p24*p32*q13 + p33*p34*q13

In [22]:
import numpy
for eps in numpy.arange(.2,.23,.001):
    #eps = eps + .01;
    P5 = [Matrix(QQ,[[eps,1-2*eps,eps],[1-2*eps,eps,eps],[0,0,1]]), Matrix(QQ,[[1-2*eps,eps,eps],[eps,eps,1-2*eps],[0,0,1]])];
    problist = list_probs(P5,12);
    high = highest_prob(problist);
    print "epsilon =",eps;
    print high[0][0],RR(high[0][1]);
    print "";

epsilon = 0.2
(0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1) 0.989972992000000

epsilon = 0.201
(0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1) 0.989922421882324

epsilon = 0.202
(0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1) 0.989872621223647

epsilon = 0.203
(0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1) 0.989823591635066

epsilon = 0.20400000000000001
(0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1) 0.989799649179576

epsilon = 0.20500000000000002
(0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1) 0.989780425759660

epsilon = 0.20600000000000002
(0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1) 0.989761655934650

epsilon = 0.20700000000000002
(0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1) 0.989743331487207

epsilon = 0.20800000000000002
(0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1) 0.989725444161607

epsilon = 0.20900000000000002
(0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1) 0.989707985667425

epsilon = 0.21000000000000002
(0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1) 0.989690947683156

epsilon = 0.21100000000000002
(0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1) 0.989674321859769

epsilon = 0.21200000000000002
(0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1

In [23]:
RRR = RealField(100);

lasthigh = [];
eps = RRR(.20314);
maxprec = 8;
incr = RRR(.000001);
    
while eps<.20315 and incr > (.1)^maxprec:
    P5 = [Matrix(RRR,[[eps,1-2*eps,eps],[1-2*eps,eps,eps],[0,0,1]]), Matrix(RRR,[[1-2*eps,eps,eps],[eps,eps,1-2*eps],[0,0,1]])];
    problist = list_probs(P5,12);
    high = highest_prob(problist);
    print "epsilon =",eps;
    print [h[0] for h in high],RRR(high[0][1]);
    if high[0][0] != lasthigh and lasthigh != []:
        print "bifurcation!";
        eps = RRR(eps - incr);
        incr = RRR(.1)*incr;
    else:
        lasthigh = high[0][0];
    eps = RRR(eps + incr);
    print "";

epsilon = 0.20314000000000000000000000000
[(0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1)] 0.98981678910332015836880088179

epsilon = 0.20314100000000000000000000000
[(0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1)] 0.98981674056827152173756178978

epsilon = 0.20314200000000000000000000000
[(0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1)] 0.98981669203399547692514562696

epsilon = 0.20314300000000000000000000000
[(0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1)] 0.98981664350049202508757445140

epsilon = 0.20314400000000000000000000000
[(0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1)] 0.98981659496776116738059601186

epsilon = 0.20314500000000000000000000000
[(0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1)] 0.98981654643580290495968375108

epsilon = 0.20314600000000000000000000000
[(0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1)] 0.98981649790461723898003680909

epsilon = 0.20314700000000000000000000000
[(0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1)] 0.98981644937420417059658002652

epsilon = 0.20314800000000000000000000000
[(0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1)] 0.98981640084456370096396394796

e

In [24]:
eps = RRR(.13889555475533735);
P6 = [Matrix(RRR,[[eps/2,1-eps,eps/2],[1-3*eps,eps,2*eps],[0,0,1]]), Matrix(RRR,[[eps,1-2*eps,eps],[(1-eps)/2,(1-eps)/2,eps],[0,0,1]])];
checkmatrices(P6);
problist = list_probs(P6,13);
high = highest_prob(problist);
#print "epsilon =",eps;
print [h[0] for h in high],RRR(high[0][1]);

[(1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0)] 0.91456563663607501448459141720

In [25]:
eps = RRR(.1);
P7 = [Matrix(RRR,[[(1-eps)/2,(1+eps)/2],[0,1]]), Matrix(RRR,[[eps,1-eps],[0,1]])];
checkmatrices(P7);
problist = list_probs(P7,7);
high = highest_prob(problist);
#print "epsilon =",eps;
print [h[0] for h in high],RRR(high[0][1]);

[(1, 1, 1, 1, 1, 1)] 0.99999900000000000000000000000

In [26]:
eps = RRR(.01);
#eps = var('eps');
#P8 = [Matrix([[eps,1-2*eps,eps],[1-2*eps,eps,eps],[0,0,1]]), Matrix([[eps,(2/3)*(1-eps),(1/3)*(1-eps)],[eps,1-2*eps,eps],[0,0,1]])];
#P8 = [Matrix([[eps,(2/3)*(1-eps),(1/3)*(1-eps)],[1-2*eps,eps,eps],[0,0,1]]), Matrix([[eps,1-2*eps,eps],[eps,1-2*eps,eps],[0,0,1]])];
P8 = [Matrix([[eps,1-2*eps,eps],[1-2*eps,eps,eps],[0,0,1]]), Matrix([[eps,(1/3)*(1-eps),(2/3)*(1-eps)],[eps,1-2*eps,eps],[0,0,1]])];

checkmatrices(P8);
problist = list_probs(P8,6);
ap0=expand(accprob(P8,"00000"));
ap1= expand(accprob(P8,"10101"));
ap2= expand(accprob(P8,"01101"));
print "00000:",ap0,"=",accprob(P8,"00000");
print "";
print "10101:",ap1,"=",accprob(P8,"10101");
print "";
print "01101:",ap2,"=",accprob(P8,"01101");
high = highest_prob(problist);
print [h[0] for h in high],RRR(high[0][1]);
#print "00000:",expand(accprob(P8,"00000"));
#print "10101:",expand(accprob(P8,"10101"));
#print "01101:",expand(accprob(P8,"01101"));

00000: 0.049009950100000000000000000000 = 0.049009950100000000000000000000

10101: 0.95569050410000000000000000000 = 0.95569050410000000000000000000

01101: 0.66536756210000000000000000000 = 0.66536756210000000000000000000
[(1, 0, 1, 0, 1)] 0.95569050410000000000000000000

In [30]:
expand((1-2*eps)^4*2*(1-eps)/3)

0.60876298560000000000000000000

In [31]:
#test Sage DFAs
A = Automaton([(0,1,0),(0,0,1),(1,2,0),(1,1,1),(2,0,0),(2,3,1)],initial_states=[0],final_states=[3]);
A.adjacency_matrix()

[1 1 0 0]
[0 1 1 0]
[1 0 0 1]
[0 0 0 0]

In [32]:
B = Automaton([(1,2,0),(1,3,1),(2,1,0),(2,2,1)],initial_states=[1],final_states=[3]);
list(B.language(5))

[[1], [0, 0, 1], [0, 1, 0, 1], [0, 0, 0, 0, 1], [0, 1, 1, 0, 1]]

In [34]:
C = automata.Word([0,1,1,0,1,1]);
list(C.language(6))

[[0, 1, 1, 0, 1, 1]]

In [36]:
C.adjacency_matrix()

[0 1 0 0 0 0 0]
[0 0 1 0 0 0 0]
[0 0 0 1 0 0 0]
[0 0 0 0 1 0 0]
[0 0 0 0 0 1 0]
[0 0 0 0 0 0 1]
[0 0 0 0 0 0 0]

In [38]:
D = automata.ContainsWord([0,1,1,0,1],input_alphabet=[0,1]);
list(D.language(7))

[[0, 1, 1, 0, 1],
 [0, 0, 1, 1, 0, 1],
 [0, 1, 1, 0, 1, 0],
 [0, 1, 1, 0, 1, 1],
 [1, 0, 1, 1, 0, 1],
 [0, 0, 0, 1, 1, 0, 1],
 [0, 0, 1, 1, 0, 1, 0],
 [0, 0, 1, 1, 0, 1, 1],
 [0, 1, 0, 1, 1, 0, 1],
 [0, 1, 1, 0, 1, 0, 0],
 [0, 1, 1, 0, 1, 0, 1],
 [0, 1, 1, 0, 1, 1, 0],
 [0, 1, 1, 0, 1, 1, 1],
 [1, 0, 0, 1, 1, 0, 1],
 [1, 0, 1, 1, 0, 1, 0],
 [1, 0, 1, 1, 0, 1, 1],
 [1, 1, 0, 1, 1, 0, 1]]